language: node_js

node_js:
  - "stable"
  - "lts/*"

branches:
  only:
    - master

cache:
  directories:
  - node_modules
git:
  depth: 3
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: develop

before_script:
  - "npm i -g gatsby-cli"
  - "yarn"

script:
  - gatsby build